sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
  - docker pull multiarch/qemu-user-static
env:
  - ADDON="python_exec"
  - ADDON="mopidy mopidy_cast"
  - ADDON="influxdb"
  - ADDON="snapcastclient"
  - ADDON="snapcastserver"
  - ADDON="nginx_proxy"
  - ADDON="certbot"
  - ADDON="syncthing"
  - ADDON="caddy_proxy"
  - ADDON="grafana"
  - ADDON="calibreweb"
  - ADDON="calibreweb_comics"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - ./build.sh $ADDON 
